/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion_computadora;

import datos.fachada.FabricaDatos;
import entidades_compartidas.*;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.fachada.FabricaLogica;
import presentacion_computadora.ventanas_auxiliares.*;

/**
 *
 * @author Lourdes Couto
 */
public class ABMFuncionalidad extends javax.swing.JFrame {
    
    int id_funcionalidad = 0;
    int id_subfuncionalidad = 0;
    DefaultTableModel modelo_tabla = new DefaultTableModel();
   
    /**
     * Creates new form ABMFuncionalidad
     */
    public ABMFuncionalidad() {
        try
        {
            initComponents();
            this.RecargarValores(0);
        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlBarra = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbAccion = new javax.swing.JComboBox<>();
        lblMensaje = new javax.swing.JLabel();
        lblFuncionalidadEliminada = new javax.swing.JLabel();
        pnlPanelSecundario = new javax.swing.JPanel();
        txtIdFuncionalidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFechaBaja = new javax.swing.JLabel();
        lblAsteriscoFechaBaja = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSubFuncionalidad = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        clnFechaAlta = new org.freixas.jcalendar.JCalendarCombo();
        clnFechaBaja = new org.freixas.jcalendar.JCalendarCombo();
        chcHaySubFuncionalidad = new javax.swing.JCheckBox();
        btnInstructivoGrilla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        pnlFondo.setBackground(new java.awt.Color(216, 207, 215));
        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        pnlBarra.setBackground(java.awt.Color.lightGray);
        pnlBarra.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBarraLayout = new javax.swing.GroupLayout(pnlBarra);
        pnlBarra.setLayout(pnlBarraLayout);
        pnlBarraLayout.setHorizontalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar))
        );
        pnlBarraLayout.setVerticalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar)))
        );

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alta de Funcionalidad.png"))); // NOI18N
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText("Elija una acción a realizar:");

        cmbAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta de Funcionalidad", "Modificación de Funcionalidad", "Baja de Funcionalidad", "Reingreso de Funcionalidad", "Reingreso de SubFuncionalidades" }));
        cmbAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccionActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblFuncionalidadEliminada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFuncionalidadEliminada.setForeground(new java.awt.Color(255, 0, 0));

        pnlPanelSecundario.setBackground(new java.awt.Color(158, 182, 203));
        pnlPanelSecundario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtIdFuncionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdFuncionalidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdFuncionalidadKeyTyped(evt);
            }
        });

        jLabel2.setText("IdFuncionalidad");

        jLabel3.setText("Titulo");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("(*)");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("(*)");

        jLabel6.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel7.setText("Fecha de Alta");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("(*)");

        lblFechaBaja.setBackground(new java.awt.Color(255, 102, 102));
        lblFechaBaja.setText("Fecha de Baja");
        lblFechaBaja.setOpaque(true);

        lblAsteriscoFechaBaja.setForeground(new java.awt.Color(255, 0, 0));
        lblAsteriscoFechaBaja.setText("(*)");

        jLabel11.setText("Lista de SubFuncionalidades (ingrese los datos en cada celda si lo desea)");

        tblSubFuncionalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Id SubFuncionalidad", "Título", "Descripción", "Fecha de Alta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSubFuncionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSubFuncionalidadKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblSubFuncionalidad);

        jLabel12.setText("Los campos marcados con");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("(*)");

        jLabel14.setText("no pueden estar vacíos.");

        btnBuscar.setText("...");
        btnBuscar.setActionCommand("ColorSubrayado");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        clnFechaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clnFechaAltaActionPerformed(evt);
            }
        });

        clnFechaBaja.setForeground(new java.awt.Color(255, 0, 0));

        chcHaySubFuncionalidad.setText("No ingresar SubFuncionalidades");
        chcHaySubFuncionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chcHaySubFuncionalidadActionPerformed(evt);
            }
        });

        btnInstructivoGrilla.setText("Ver Instructivo de la Grilla");
        btnInstructivoGrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructivoGrillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPanelSecundarioLayout = new javax.swing.GroupLayout(pnlPanelSecundario);
        pnlPanelSecundario.setLayout(pnlPanelSecundarioLayout);
        pnlPanelSecundarioLayout.setHorizontalGroup(
            pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                        .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addComponent(jLabel6)
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clnFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                        .addComponent(lblFechaBaja)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblAsteriscoFechaBaja))
                                    .addComponent(clnFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                        .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(txtIdFuncionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(0, 432, Short.MAX_VALUE))
                            .addComponent(txtTitulo)))
                    .addComponent(jScrollPane2)
                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(39, 39, 39)
                        .addComponent(chcHaySubFuncionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelSecundarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInstructivoGrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPanelSecundarioLayout.setVerticalGroup(
            pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdFuncionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(chcHaySubFuncionalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstructivoGrilla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(lblFechaBaja)
                    .addComponent(lblAsteriscoFechaBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clnFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clnFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPanelSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(cmbAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFuncionalidadEliminada)))))
                .addGap(25, 25, 25))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblFuncionalidadEliminada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        try
        {
            this.dispose();
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        try
        {
              /*Re-establezco la ubicación de los controles a medida que voy modificando el tamaño de la pantalla*/
            int altura, largo;
            Point p;

            altura = this.getHeight();
            largo = this.getWidth();
        
            this.lblTitulo.setSize(largo, 29);
            this.pnlFondo.setSize(largo, altura);
            this.pnlBarra.setSize(largo, 31);
            this.btnAceptar.setSize(77,27);
            //this.txtTipoLetra.setSize(201,28);
            
            p = new Point(1, (altura - 70));
            this.pnlBarra.setLocation(p);
            p = new Point(largo - (btnCancelar.getWidth() + 20), 1);
            this.btnCancelar.setLocation(p);
            p = new Point(largo - (btnCancelar.getWidth() +  btnAceptar.getWidth() + 20), 2);
            this.btnAceptar.setLocation(p);
            p = new Point(26,86);
            this.pnlPanelSecundario.setLocation(p);
            p = new Point(23,53);
            this.jLabel1.setLocation(p);
             p = new Point(205,48);
            this.cmbAccion.setLocation(p);
            
           // this.txtDescripcion.setText("" + this.cmbAccion.getLocation());
        }
       catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_formComponentResized

    private void cmbAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccionActionPerformed
        // TODO add your handling code here:
        try
        {
            switch(this.cmbAccion.getSelectedIndex())
            {
                case 0:
                    this.RecargarValores(0);
                break;
                case 1:
                    this.RecargarValores(1);
                break;
                case 2:
                   this.RecargarValores(2);
                break;
                case 3:
                    this.RecargarValores(3);
                default:
                   this.RecargarValores(4);
            }
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
        
    }//GEN-LAST:event_cmbAccionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try
        {
          ConsultaFuncionalidad c = new ConsultaFuncionalidad(this);
          c.setVisible(true);
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        try
        {
            String titulo = "";
            String descripcion = "";
            Date fecha_hecho = new Date();
            Date fecha_baja = new Date();
            Funcionalidad f = new Funcionalidad();
            ArrayList<SubFuncionalidad> lista_sub_funcionalidad = new ArrayList(); 
            boolean estaVacio = false;
            int reintegro = 0;
            String mensaje_advertencia = "";
            
          //  DefaultTableModel modelo = new DefaultTableModel();
            
              if(this.chcHaySubFuncionalidad.isSelected() == false)
              {
                for(int i = 0; (i< this.tblSubFuncionalidad.getRowCount() && estaVacio == false); i++)
                {           
                      if(this.tblSubFuncionalidad.getValueAt(i, 1).equals(""))
                      {
                          estaVacio = true;
                      }
                }
              }
         
            if(this.txtTitulo.getText().equals(""))
            {
                this.lblMensaje.setText("El campo Título no puede estar vacío");
                this.lblMensaje.setForeground(Color.RED);
            }
            else if(estaVacio == true && this.chcHaySubFuncionalidad.isSelected() == false )
            {
               this.lblMensaje.setText("El campo Título no puede estar vacío para todas las celdas de la tabla de Subfuncionalidades");
               this.lblMensaje.setForeground(Color.RED);
            }
            else
            {
                      id_funcionalidad = Integer.parseInt(this.txtIdFuncionalidad.getText());  
                      titulo = this.txtTitulo.getText();
                      descripcion = this.txtDescripcion.getText();
                      fecha_hecho = this.clnFechaAlta.getDate();
                      fecha_baja = this.clnFechaBaja.getDate();
                     
                      if(this.chcHaySubFuncionalidad.isSelected() == false)
                      {
                            for(int i = 0; i< this.tblSubFuncionalidad.getRowCount(); i++)
                            {
                                SubFuncionalidad sf = new SubFuncionalidad();

                                sf.setId((int)this.tblSubFuncionalidad.getValueAt(i, 0));
                                sf.setTitulo((String)this.tblSubFuncionalidad.getValueAt(i, 1));
                                sf.setDescripcion((String)this.tblSubFuncionalidad.getValueAt(i,2));
                                sf.setFecha_hecho((Date)this.tblSubFuncionalidad.getValueAt(i, 3));

                                lista_sub_funcionalidad.add(sf);
                            }
                      }
                            f = new Funcionalidad(id_funcionalidad, titulo, descripcion, fecha_hecho, fecha_baja, lista_sub_funcionalidad); 
                      
                switch(this.cmbAccion.getSelectedIndex())
                {
                    case 0:
                  
                       if(FabricaLogica.getControladorFuncionalidad().AltaFuncionalidad(f)>0)
                       {
                           this.lblMensaje.setText("Alta de Funcionalidad exitosa");
                           this.lblMensaje.setForeground(Color.BLACK);
                           this.RecargarValores(0);
                       }
                       else
                       {
                           this.lblMensaje.setText("Alta de Funcionalidad NO exitosa");
                           this.lblMensaje.setForeground(Color.RED);
                       }
                       
                    break;
                  
                    case 1:
               
                    mensaje_advertencia = "Usted al realizar una modificación va a sobrescribir los datos ya existentes del IdFuncionalidad: " + id_funcionalidad + " ¿Está seguro que desea modificar este registro?";
                
                    if(JOptionPane.showConfirmDialog(this, mensaje_advertencia, "Mensaje de Advertencia" , 0, 2) == 0)
                    {
                           if(FabricaLogica.getControladorFuncionalidad().ModificarFuncionalidad(f)>0)
                           {
                               this.lblMensaje.setText("Modificación de Funcionalidad exitosa");
                               this.lblMensaje.setForeground(Color.BLACK);
                               this.RecargarValores(1);
                           }
                           else
                           {
                               this.lblMensaje.setText("Modificación de Funcionalidad NO exitosa");
                               this.lblMensaje.setForeground(Color.RED);
                           }

                    }      
                    break;
                   
                    case 2:
                      
                    mensaje_advertencia = "Usted al realizar una baja va a eliminar los datos ya existentes del IdFuncionalidad: " + id_funcionalidad + " ¿Está seguro que desea dar de baja este registro?";
                
                    if(JOptionPane.showConfirmDialog(this, mensaje_advertencia, "Mensaje de Advertencia" , 0, 2) == 0)
                    {   
                       if(FabricaLogica.getControladorFuncionalidad().BajaFuncionalidad(f)>0)
                       {
                           this.lblMensaje.setText("Baja de Funcionalidad exitosa");
                           this.lblMensaje.setForeground(Color.BLACK);
                           this.RecargarValores(2);
                       }
                       else
                       {
                           this.lblMensaje.setText("Baja de Funcionalidad NO exitosa");
                           this.lblMensaje.setForeground(Color.RED);
                       }
                    }
                    break;
                    case 3:
                        
                       if(FabricaLogica.getControladorFuncionalidad().ReingresarFuncionalidad(f)>0)
                       {
                           this.lblMensaje.setText("Reingreso de Funcionalidad exitosa");
                           this.lblMensaje.setForeground(Color.BLACK);
                           this.RecargarValores(3);
                       }
                       else
                       {
                           this.lblMensaje.setText("Reingreso de Funcionalidad NO exitosa");
                           this.lblMensaje.setForeground(Color.RED);
                       }

                    break;
                    default:
                        
                        for(SubFuncionalidad sf : lista_sub_funcionalidad)
                        {
                            reintegro = FabricaLogica.getControladorSubFuncionalidad().ReingresarSubFuncionalidad(id_funcionalidad, sf);
                        }
                        
                        if(reintegro>0)
                       {
                           this.lblMensaje.setText("Reingreso de la lista de Sub-Funcionalidad exitoso");
                           this.lblMensaje.setForeground(Color.BLACK);
                           this.RecargarValores(4);
                       }
                       else
                       {
                           this.lblMensaje.setText("Reingreso de la lista de Sub-Funcionalidad NO exitoso");
                           this.lblMensaje.setForeground(Color.RED);
                       }
 
                      
                }
            }
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtIdFuncionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFuncionalidadKeyTyped
        // TODO add your handling code here:
        try
        {
              char caracter = evt.getKeyChar(); 
              
              if(Character.isLetter(caracter)) 
              { 
                  getToolkit().beep(); 
                  evt.consume(); 
                  this.lblMensaje.setText("Ingrese sólamente números"); 
                //  buscar = false;
              }
              else
              {
                  this.lblMensaje.setText("");
              }
             
        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }        
    }//GEN-LAST:event_txtIdFuncionalidadKeyTyped

    private void clnFechaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clnFechaAltaActionPerformed
        // TODO add your handling code here:
        try
        {
            for(int i=0; i<this.tblSubFuncionalidad.getRowCount(); i++)
            {
                this.tblSubFuncionalidad.setValueAt(clnFechaAlta.getDate(), i, 3);
            }
        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_clnFechaAltaActionPerformed

    private void tblSubFuncionalidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSubFuncionalidadKeyReleased
        // TODO add your handling code here:
        try
        {
            if(evt.getKeyCode() == 10)
            {
              id_subfuncionalidad++;
              Object[] sf_vector = {id_subfuncionalidad, "","",clnFechaAlta.getDate()};
              modelo_tabla.addRow(sf_vector);
              this.tblSubFuncionalidad.setModel(modelo_tabla);
            }
            else if(evt.getKeyCode() == 17)
            {
                modelo_tabla.removeRow(this.tblSubFuncionalidad.getSelectedRow());
                if(cmbAccion.getSelectedIndex() == 0)
                {
                    id_subfuncionalidad--;

                    for(int i=0; i<id_subfuncionalidad; i++)
                    {
                        modelo_tabla.setValueAt(i + 1, i, 0);
                    }
                }
                this.tblSubFuncionalidad.setModel(modelo_tabla);
            }
        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }        
    }//GEN-LAST:event_tblSubFuncionalidadKeyReleased

    private void txtIdFuncionalidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdFuncionalidadKeyReleased
        // TODO add your handling code here:
        try
        {
           this.BuscarFuncionalidad();
        }
        catch(Exception ex)
        {
          this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_txtIdFuncionalidadKeyReleased

    private void chcHaySubFuncionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chcHaySubFuncionalidadActionPerformed
        // TODO add your handling code here:
        try
        {
             if(this.chcHaySubFuncionalidad.isSelected() == true)
             {
                 modelo_tabla = new DefaultTableModel();
                 Object[] columna_tabla = {"Id_SubFuncionalidad", "Titulo","Descripcion","Fecha de Alta"};
                 modelo_tabla.setColumnIdentifiers(columna_tabla);
                 this.tblSubFuncionalidad.setEnabled(false);
             }
             else
             {
                  Object[] sf_vector = {id_subfuncionalidad, "","",clnFechaAlta.getDate()};
                  modelo_tabla.addRow(sf_vector);
                  this.tblSubFuncionalidad.setEnabled(true);
             }
             this.tblSubFuncionalidad.setModel(modelo_tabla);
        }
         catch(Exception ex)
        {
          this.lblMensaje.setText(ex.toString());
        }
        
    }//GEN-LAST:event_chcHaySubFuncionalidadActionPerformed

    private void btnInstructivoGrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructivoGrillaActionPerformed
        // TODO add your handling code here:
        try
        {
            new VentanaInstructivo().setVisible(true);
        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_btnInstructivoGrillaActionPerformed

    private void RecargarValores(int pAccion)
    {
        /*Asigno o limpio valores*/
         id_funcionalidad = FabricaDatos.getControladorFuncionalidad().VerSiguienteIdFuncionalidad();
         id_subfuncionalidad = FabricaDatos.getControladorSubFuncionalidad().VerSiguienteIdSubFuncionalidad(id_funcionalidad);
         this.txtIdFuncionalidad.setText("" + id_funcionalidad);            
         this.txtTitulo.setText("");
         this.txtDescripcion.setText("");
         this.lblFuncionalidadEliminada.setText("");
         if(modelo_tabla.getRowCount()>0)
         {
            modelo_tabla = new DefaultTableModel();
         }
         Object[] columna_tabla = {"Id_SubFuncionalidad", "Titulo","Descripcion","Fecha de Alta"};
         Object[] sf_vector = {id_subfuncionalidad, "","",clnFechaAlta.getDate()};
         modelo_tabla.setColumnIdentifiers(columna_tabla);
         modelo_tabla.addRow(sf_vector);
         this.tblSubFuncionalidad.setModel(modelo_tabla);
        
         switch(pAccion)
            {
                case 0:
                 
                 /*Habilito o Deshabilito botones*/
                 this.clnFechaBaja.setVisible(false); 
                 this.lblFechaBaja.setVisible(false);
                 this.lblAsteriscoFechaBaja.setVisible(false);
                 this.lblFuncionalidadEliminada.setVisible(false);
                 this.txtIdFuncionalidad.setEnabled(false);
                 this.btnBuscar.setEnabled(false);
                 this.txtTitulo.setEnabled(true);
                 this.txtDescripcion.setEnabled(true);
                 this.chcHaySubFuncionalidad.setEnabled(true);
                 this.tblSubFuncionalidad.setEnabled(true);
                 this.clnFechaAlta.setEnabled(true);
                 this.btnAceptar.setEnabled(true);
                 this.chcHaySubFuncionalidad.setSelected(false);
                 this.txtTitulo.setForeground(Color.BLACK);
                 this.txtDescripcion.setForeground(Color.BLACK);
                 this.tblSubFuncionalidad.setForeground(Color.BLACK);
                 this.clnFechaAlta.setForeground(Color.BLACK);
                 lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alta de Funcionalidad.png")));
                break;
                case 1:

                   this.txtIdFuncionalidad.setEnabled(true);
                   this.btnBuscar.setEnabled(true);
                   this.txtTitulo.setEnabled(false);
                   this.txtDescripcion.setEnabled(false);
                   this.chcHaySubFuncionalidad.setEnabled(false);
                   this.chcHaySubFuncionalidad.setSelected(false);
                   this.tblSubFuncionalidad.setEnabled(false);
                   this.clnFechaAlta.setEnabled(false);
                   this.clnFechaBaja.setVisible(false);
                   this.btnAceptar.setEnabled(false);
                   this.txtTitulo.setForeground(Color.BLACK);
                   this.txtDescripcion.setForeground(Color.BLACK);
                   this.tblSubFuncionalidad.setForeground(Color.BLACK);
                   this.clnFechaAlta.setForeground(Color.BLACK);
                   this.lblFuncionalidadEliminada.setVisible(false);
                   this.lblFuncionalidadEliminada.setText("");
                   lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modificación de Funcionalidad.png")));
                break;
                case 2: 
                 this.txtIdFuncionalidad.setEnabled(true);
                 this.btnBuscar.setEnabled(true);
                 this.txtTitulo.setEnabled(false);
                 this.txtDescripcion.setEnabled(false);
                 this.chcHaySubFuncionalidad.setEnabled(false);
                 this.chcHaySubFuncionalidad.setSelected(false);
                 this.tblSubFuncionalidad.setEnabled(false);
                 this.clnFechaAlta.setEnabled(false);
                 this.clnFechaBaja.setVisible(true);
                 this.btnAceptar.setEnabled(false);
                 this.lblFechaBaja.setVisible(true);
                 this.lblAsteriscoFechaBaja.setVisible(true);
                 this.clnFechaBaja.setVisible(true);
                 this.btnAceptar.setEnabled(false);
                 this.txtTitulo.setForeground(Color.BLACK);
                 this.txtDescripcion.setForeground(Color.BLACK);
                 this.tblSubFuncionalidad.setForeground(Color.BLACK);
                 this.clnFechaAlta.setForeground(Color.BLACK);
                 this.clnFechaBaja.setForeground(Color.RED);
                 this.lblFuncionalidadEliminada.setVisible(false);
                 this.lblFuncionalidadEliminada.setText("");
                 lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baja de Funcionalidad.png")));
                break;
                case 3:
                  this.lblFechaBaja.setVisible(true);
                   this.lblAsteriscoFechaBaja.setVisible(true);
                   this.clnFechaBaja.setVisible(true);
                   this.lblFuncionalidadEliminada.setVisible(false);
                   this.txtIdFuncionalidad.setEnabled(true);
                   this.btnBuscar.setEnabled(true);
                   this.txtTitulo.setEnabled(false);
                   this.txtDescripcion.setEnabled(false);
                   this.chcHaySubFuncionalidad.setEnabled(false);
                   this.chcHaySubFuncionalidad.setSelected(false);
                   this.tblSubFuncionalidad.setEnabled(false);
                   this.clnFechaAlta.setEnabled(false);
                   this.clnFechaBaja.setEnabled(false);
                   this.btnAceptar.setEnabled(false);
                   this.clnFechaBaja.setForeground(Color.RED);
                   this.lblFuncionalidadEliminada.setText("");
                   lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reingreso de Funcionalidad.png")));      
                break;    
                default:
                   this.txtIdFuncionalidad.setEnabled(true);
                   this.btnBuscar.setEnabled(true);
                   this.txtTitulo.setEnabled(false);
                   this.txtDescripcion.setEnabled(false);
                   this.chcHaySubFuncionalidad.setEnabled(false);
                   this.chcHaySubFuncionalidad.setSelected(false);
                   this.tblSubFuncionalidad.setEnabled(false);
                   this.clnFechaAlta.setEnabled(false);
                   this.clnFechaBaja.setVisible(false);
                   this.btnAceptar.setEnabled(false);
                   this.txtTitulo.setForeground(Color.BLACK);
                   this.txtDescripcion.setForeground(Color.BLACK);
                   this.clnFechaAlta.setForeground(Color.BLACK);
                   this.lblFuncionalidadEliminada.setVisible(false);
                   this.lblFuncionalidadEliminada.setText("");
                   lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reingreso de SubFuncionalidad.png")));
                 
            }
    }
    
    private void BuscarFuncionalidad()
    {
         Funcionalidad f = new Funcionalidad();
        
            if(this.txtIdFuncionalidad.getText().equals("") == false)
            {
                  this.id_funcionalidad = Integer.parseInt(this.txtIdFuncionalidad.getText());
                  if(this.cmbAccion.getSelectedIndex() == 1 || this.cmbAccion.getSelectedIndex() == 2)
                  {
                     f = FabricaLogica.getControladorFuncionalidad().BuscarFuncionalidadPorId(this.id_funcionalidad);
                  }
                  else if(this.cmbAccion.getSelectedIndex() == 4)
                  {
                      f = FabricaLogica.getControladorFuncionalidad().BuscarFuncionalidadConSubFuncionalidadEliminados(id_funcionalidad);
                  
                  }
                  else
                  {
                     f = FabricaLogica.getControladorFuncionalidad().BuscarFuncionalidadEliminadaPorId(id_funcionalidad);
                  }
                  
                  if(f!=null)
                  {
                  
                      this.txtTitulo.setText(f.getTitulo());
                      this.txtDescripcion.setText(f.getDescripcion());
                      this.clnFechaAlta.setDate(f.getFecha_hecho());
                      
                      modelo_tabla = new DefaultTableModel();
                      
                      if(this.cmbAccion.getSelectedIndex() == 1 || this.cmbAccion.getSelectedIndex() == 2)
                      {
                         this.lblFuncionalidadEliminada.setVisible(false);
                         this.lblFuncionalidadEliminada.setText("");
                         this.txtTitulo.setForeground(Color.BLACK);
                         this.txtDescripcion.setForeground(Color.BLACK);
                         this.tblSubFuncionalidad.setForeground(Color.BLACK);
                         this.clnFechaAlta.setForeground(Color.BLACK);
                      
                          Object[] columna_tabla = {"Id_SubFuncionalidad", "Titulo","Descripcion","Fecha de Alta"};
                          modelo_tabla.setColumnIdentifiers(columna_tabla);
                          for(SubFuncionalidad sf : f.getSub_funcionalidad())
                          {
                               Object[] vector ={sf.getId(), sf.getTitulo(), sf.getDescripcion(), sf.getFecha_hecho()};
                               modelo_tabla.addRow(vector);
                               id_subfuncionalidad = sf.getId();
                          }
                          if(this.cmbAccion.getSelectedIndex() == 1)
                          {
                               this.txtTitulo.setEnabled(true);
                               this.txtDescripcion.setEnabled(true);
                               this.chcHaySubFuncionalidad.setEnabled(true);
                               this.chcHaySubFuncionalidad.setSelected(false);
                               this.tblSubFuncionalidad.setEnabled(true);
                               this.clnFechaAlta.setEnabled(true);
                          }
                          else
                          { 
                               this.clnFechaBaja.setEnabled(true);
                          }
                      
                      }
                      else
                      {
                            Object[] columna_tabla = {"Id_SubFuncionalidad", "Titulo","Descripcion","Fecha de Alta","Fecha de Baja"};
                            modelo_tabla.setColumnIdentifiers(columna_tabla);
                            for(SubFuncionalidad sf : f.getSub_funcionalidad())
                            {
                                 Object[] vector ={sf.getId(), sf.getTitulo(), sf.getDescripcion(), sf.getFecha_hecho(), sf.getFecha_baja()};
                                 modelo_tabla.addRow(vector);
                            }
                               this.tblSubFuncionalidad.setForeground(Color.RED);

                             if(this.cmbAccion.getSelectedIndex() == 3)
                             {
                               this.lblFuncionalidadEliminada.setVisible(true);
                               this.lblFuncionalidadEliminada.setText("ELIMINAD0");
                               this.txtTitulo.setForeground(Color.RED);
                               this.txtDescripcion.setForeground(Color.RED);
                               this.clnFechaAlta.setForeground(Color.RED);
                             }
                      }
                        this.tblSubFuncionalidad.setModel(modelo_tabla);
                        this.btnAceptar.setEnabled(true);
                 }
                 else
                 {
                      this.txtTitulo.setText("");
                      this.txtDescripcion.setText("");
                      this.clnFechaAlta.setDate(new Date());
                      
                      modelo_tabla = new DefaultTableModel();
                      Object[] columna_tabla = {"Id_SubFuncionalidad", "Titulo","Descripcion","Fecha de Alta"};
                      this.tblSubFuncionalidad.setModel(modelo_tabla);
                      
                          this.txtTitulo.setEnabled(false);
                          this.txtDescripcion.setEnabled(false);
                          this.clnFechaAlta.setEnabled(false);
                          this.clnFechaBaja.setEnabled(false);
                          this.btnAceptar.setEnabled(false);
                      
                      this.lblMensaje.setText("No existe una funcionalidad para el Id ingresado. Prueba con otro Id.");
                 }
           }
    }
    
    public void EstablecerIdFuncionalidad(int pIdFuncionalidad)
    {
        this.txtIdFuncionalidad.setText("" + pIdFuncionalidad);
        this.BuscarFuncionalidad();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMFuncionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMFuncionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMFuncionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMFuncionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMFuncionalidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInstructivoGrilla;
    private javax.swing.JCheckBox chcHaySubFuncionalidad;
    private org.freixas.jcalendar.JCalendarCombo clnFechaAlta;
    private org.freixas.jcalendar.JCalendarCombo clnFechaBaja;
    private javax.swing.JComboBox<String> cmbAccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAsteriscoFechaBaja;
    private javax.swing.JLabel lblFechaBaja;
    private javax.swing.JLabel lblFuncionalidadEliminada;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlPanelSecundario;
    private javax.swing.JTable tblSubFuncionalidad;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtIdFuncionalidad;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
