/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion_computadora;

import datos.fachada.FabricaDatos;
import entidades_compartidas.*;
import java.awt.Color;
import java.awt.Point;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.fachada.FabricaLogica;

/**
 *
 * @author ubuntulourdes
 */
public class ABMTipoPermiso extends javax.swing.JFrame {

    int id_tipo_permiso = 0;
    
    /**
     * Creates new form ModeloForm
     */
    public ABMTipoPermiso() {
        initComponents();
        this.RecargarValores(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlBarra = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbAccion = new javax.swing.JComboBox<>();
        lblMensaje = new javax.swing.JLabel();
        lblFuncionalidadEliminada = new javax.swing.JLabel();
        pnlPanelSecundario = new javax.swing.JPanel();
        txtIdTipoPermiso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFechaBaja = new javax.swing.JLabel();
        lblAsteriscoFechaBaja = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        clnFechaAlta = new org.freixas.jcalendar.JCalendarCombo();
        clnFechaBaja = new org.freixas.jcalendar.JCalendarCombo();
        jLabel9 = new javax.swing.JLabel();
        txtDescAbreviada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        pnlFondo.setBackground(new java.awt.Color(216, 207, 215));
        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        pnlBarra.setBackground(java.awt.Color.lightGray);
        pnlBarra.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBarraLayout = new javax.swing.GroupLayout(pnlBarra);
        pnlBarra.setLayout(pnlBarraLayout);
        pnlBarraLayout.setHorizontalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar))
        );
        pnlBarraLayout.setVerticalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar)))
        );

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alta de Tipo de Permiso.png"))); // NOI18N
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setText("Elija una acción a realizar:");

        cmbAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta de Tipo de Permiso", "Modificación de Tipo de Permiso", "Baja de Tipo de Permiso", "Reingreso de Tipo de Permiso" }));
        cmbAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccionActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblFuncionalidadEliminada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFuncionalidadEliminada.setForeground(new java.awt.Color(255, 0, 0));

        pnlPanelSecundario.setBackground(new java.awt.Color(158, 182, 203));
        pnlPanelSecundario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtIdTipoPermiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdTipoPermisoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdTipoPermisoKeyTyped(evt);
            }
        });

        jLabel2.setText("IdTipoPermiso");

        jLabel3.setText("Nombre");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("(*)");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("(*)");

        jLabel6.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel7.setText("Fecha de Alta");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("(*)");

        lblFechaBaja.setBackground(new java.awt.Color(255, 102, 102));
        lblFechaBaja.setText("Fecha de Baja");
        lblFechaBaja.setOpaque(true);

        lblAsteriscoFechaBaja.setForeground(new java.awt.Color(255, 0, 0));
        lblAsteriscoFechaBaja.setText("(*)");

        jLabel12.setText("Los campos marcados con");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("(*)");

        jLabel14.setText("no pueden estar vacíos.");

        btnBuscar.setText("...");
        btnBuscar.setActionCommand("ColorSubrayado");
        btnBuscar.setEnabled(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        clnFechaBaja.setForeground(new java.awt.Color(255, 0, 0));

        jLabel9.setText("Descripción Abreviada");

        javax.swing.GroupLayout pnlPanelSecundarioLayout = new javax.swing.GroupLayout(pnlPanelSecundario);
        pnlPanelSecundario.setLayout(pnlPanelSecundarioLayout);
        pnlPanelSecundarioLayout.setHorizontalGroup(
            pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                        .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(txtIdTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(txtTitulo)))
                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                        .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtDescAbreviada, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clnFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                                        .addComponent(lblFechaBaja)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAsteriscoFechaBaja))
                                    .addComponent(clnFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPanelSecundarioLayout.setVerticalGroup(
            pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdTipoPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescAbreviada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblFechaBaja)
                    .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(lblAsteriscoFechaBaja)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clnFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clnFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPanelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFuncionalidadEliminada, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(pnlBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(lblFuncionalidadEliminada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(pnlPanelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        try
        {
            this.dispose();
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        try
        {
            String titulo = "";
            String descripcion = "";
            String desc_abreviada = "";
            Date fecha_hecho = new Date();
            Date fecha_baja = new Date();
            TipoPermiso t = new TipoPermiso();
            boolean estaVacio = false;
            int reintegro = 0;
            String mensaje_advertencia = "";

            //  DefaultTableModel modelo = new DefaultTableModel();

            if(this.txtTitulo.getText().equals(""))
            {
                this.lblMensaje.setText("El campo Nombre no puede estar vacío");
                this.lblMensaje.setForeground(Color.RED);
            }
            else if(this.txtDescAbreviada.getText().equals(""))
            {
                 this.lblMensaje.setText("El campo Descripción Abreviada no puede estar vacío");
                 this.lblMensaje.setForeground(Color.RED);
            }
            else
            {
                this.id_tipo_permiso = Integer.parseInt(this.txtIdTipoPermiso.getText());
                titulo = this.txtTitulo.getText();
                descripcion = this.txtDescripcion.getText();
                desc_abreviada = this.txtDescAbreviada.getText();
                fecha_hecho = this.clnFechaAlta.getDate();
                fecha_baja = this.clnFechaBaja.getDate();

                t = new TipoPermiso(this.id_tipo_permiso, titulo, descripcion, desc_abreviada, fecha_hecho, fecha_baja);

                switch(this.cmbAccion.getSelectedIndex())
                {
                    case 0:

                    if(FabricaLogica.getControladorTipoPermiso().AltaTipoPermiso(t)>0)
                    {
                        this.lblMensaje.setText("Alta de Tipo de Permiso exitosa");
                        this.lblMensaje.setForeground(Color.BLACK);
                        this.RecargarValores(0);
                    }
                    else
                    {
                        this.lblMensaje.setText("Alta de Tipo de Permiso NO exitosa");
                        this.lblMensaje.setForeground(Color.RED);
                    }

                    break;

                    case 1:

                    mensaje_advertencia = "Usted al realizar una modificación va a sobrescribir los datos ya existentes del IdTipoPermiso: " + this.id_tipo_permiso + " ¿Está seguro que desea modificar este registro?";

                    if(JOptionPane.showConfirmDialog(this, mensaje_advertencia, "Mensaje de Advertencia" , 0, 2) == 0)
                    {
                        if(FabricaLogica.getControladorTipoPermiso().ModificarTipoPermiso(t)>0)
                        {
                            this.lblMensaje.setText("Modificación de Tipo de Permiso exitosa");
                            this.lblMensaje.setForeground(Color.BLACK);
                            this.RecargarValores(1);
                        }
                        else
                        {
                            this.lblMensaje.setText("Modificación de Tipo de Permiso NO exitosa");
                            this.lblMensaje.setForeground(Color.RED);
                        }

                    }
                    break;

                    case 2:

                    mensaje_advertencia = "Usted al realizar una baja va a eliminar los datos ya existentes del IdTipoPermiso: " + this.id_tipo_permiso + " ¿Está seguro que desea dar de baja este registro?";

                    if(JOptionPane.showConfirmDialog(this, mensaje_advertencia, "Mensaje de Advertencia" , 0, 2) == 0)
                    {
                        if(FabricaLogica.getControladorTipoPermiso().BajaTipoPermiso(t)>0)
                        {
                            this.lblMensaje.setText("Baja de Tipo de Permiso exitosa");
                            this.lblMensaje.setForeground(Color.BLACK);
                            this.RecargarValores(2);
                        }
                        else
                        {
                            this.lblMensaje.setText("Baja de Tipo de Permiso NO exitosa");
                            this.lblMensaje.setForeground(Color.RED);
                        }
                    }
                    break;
               
                    default:

                    if(FabricaLogica.getControladorTipoPermiso().ReingresarTipoPermiso(t)>0)
                    {
                        this.lblMensaje.setText("Reingreso de Tipo de Permiso exitosa");
                        this.lblMensaje.setForeground(Color.BLACK);
                        this.RecargarValores(3);
                    }
                    else
                    {
                        this.lblMensaje.setText("Reingreso de Tipo de Permiso NO exitosa");
                        this.lblMensaje.setForeground(Color.RED);
                    }

                }
            }
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccionActionPerformed
        // TODO add your handling code here:
        try
        {
            switch(this.cmbAccion.getSelectedIndex())
            {
                case 0:
                this.RecargarValores(0);
                break;
                case 1:
                this.RecargarValores(1);
                break;
                case 2:
                this.RecargarValores(2); 
                default:
                this.RecargarValores(3);
            }
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }

    }//GEN-LAST:event_cmbAccionActionPerformed

    private void txtIdTipoPermisoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdTipoPermisoKeyReleased
        // TODO add your handling code here:
        try
        {
            this.BuscarFuncionalidad();
        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_txtIdTipoPermisoKeyReleased

    private void txtIdTipoPermisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdTipoPermisoKeyTyped
        // TODO add your handling code here:
        try
        {
            char caracter = evt.getKeyChar();

            if(Character.isLetter(caracter))
            {
                getToolkit().beep();
                evt.consume();
                this.lblMensaje.setText("Ingrese sólamente números");
                //  buscar = false;
            }
            else
            {
                this.lblMensaje.setText("");
            }

        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_txtIdTipoPermisoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try
        {
//            ConsultaFuncionalidad c = new ConsultaFuncionalidad(this);
//            c.setVisible(true);
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        try
        {
              /*Re-establezco la ubicación de los controles a medida que voy modificando el tamaño de la pantalla*/
            int altura, largo;
            Point p;

            altura = this.getHeight();
            largo = this.getWidth();
        
            this.lblTitulo.setSize(largo, 29);
            this.pnlFondo.setSize(largo, altura);
            this.pnlBarra.setSize(largo, 31);
            this.btnAceptar.setSize(77,27);
            //this.txtTipoLetra.setSize(201,28);
            
            p = new Point(1, (altura - 70));
            this.pnlBarra.setLocation(p);
            p = new Point(largo - (btnCancelar.getWidth() + 20), 1);
            this.btnCancelar.setLocation(p);
            p = new Point(largo - (btnCancelar.getWidth() +  btnAceptar.getWidth() + 20), 2);
            this.btnAceptar.setLocation(p);
            p = new Point(26,86);
            this.pnlPanelSecundario.setLocation(p);
            p = new Point(23,53);
            this.jLabel1.setLocation(p);
           //  p = new Point(205,48);
           // this.cmbAccion.setLocation(p);
            
           // this.txtDescripcion.setText("" + this.cmbAccion.getLocation());
        }
       catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
        
    }//GEN-LAST:event_formComponentResized

     private void RecargarValores(int pAccion)
    {
        /*Asigno o limpio valores*/
         id_tipo_permiso = FabricaLogica.getControladorTipoPermiso().VerSiguienteId();
         this.txtIdTipoPermiso.setText("" + id_tipo_permiso);            
         this.txtTitulo.setText("");
         this.txtDescripcion.setText("");
         this.txtDescAbreviada.setText("");
         this.lblFuncionalidadEliminada.setText("");
        
         switch(pAccion)
            {
                case 0:
                 
                 /*Habilito o Deshabilito botones*/
                 this.clnFechaBaja.setVisible(false); 
                 this.lblFechaBaja.setVisible(false);
                 this.lblAsteriscoFechaBaja.setVisible(false);
                 this.lblFuncionalidadEliminada.setVisible(false);
                 this.txtIdTipoPermiso.setEnabled(false);
                 this.btnBuscar.setEnabled(false);
                 this.txtTitulo.setEnabled(true);
                 this.txtDescripcion.setEnabled(true);
                 this.txtDescAbreviada.setEnabled(true);
                 this.clnFechaAlta.setEnabled(true);
                 this.btnAceptar.setEnabled(true);
                 this.txtTitulo.setForeground(Color.BLACK);
                 this.txtDescripcion.setForeground(Color.BLACK);
                 this.txtDescAbreviada.setForeground(Color.BLACK);
                 this.clnFechaAlta.setForeground(Color.BLACK);
                 lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alta de Tipo de Permiso.png")));
                break;
                case 1:

                   this.txtIdTipoPermiso.setEnabled(true);
                   this.btnBuscar.setEnabled(true);
                   this.txtTitulo.setEnabled(false);
                   this.txtDescripcion.setEnabled(false);
                   this.txtDescAbreviada.setEnabled(false);
                   this.clnFechaAlta.setEnabled(false);
                   this.clnFechaBaja.setVisible(false);
                   this.btnAceptar.setEnabled(false);
                   this.txtTitulo.setForeground(Color.BLACK);
                   this.txtDescripcion.setForeground(Color.BLACK);
                   this.txtDescAbreviada.setForeground(Color.BLACK);
                   this.clnFechaAlta.setForeground(Color.BLACK);
                   this.lblFuncionalidadEliminada.setVisible(false);
                   this.lblFuncionalidadEliminada.setText("");
                   lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modificación de Tipo de Permiso.png")));
                break;
                case 2: 
                 this.txtIdTipoPermiso.setEnabled(true);
                 this.btnBuscar.setEnabled(true);
                 this.txtTitulo.setEnabled(false);
                 this.txtDescripcion.setEnabled(false);
                 this.txtDescAbreviada.setEnabled(false);
                 this.clnFechaAlta.setEnabled(false);
                 this.clnFechaBaja.setVisible(true);
                 this.btnAceptar.setEnabled(false);
                 this.lblFechaBaja.setVisible(true);
                 this.lblAsteriscoFechaBaja.setVisible(true);
                 this.clnFechaBaja.setVisible(true);
                 this.btnAceptar.setEnabled(false);
                 this.txtTitulo.setForeground(Color.BLACK);
                 this.txtDescripcion.setForeground(Color.BLACK);
                 this.txtDescAbreviada.setForeground(Color.BLACK);
                 this.clnFechaAlta.setForeground(Color.BLACK);
                 this.clnFechaBaja.setForeground(Color.RED);
                 this.lblFuncionalidadEliminada.setVisible(false);
                 this.lblFuncionalidadEliminada.setText("");
                 lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Baja de Tipo de Permiso.png")));
                break;
               default:
               this.lblFechaBaja.setVisible(true);
               this.lblAsteriscoFechaBaja.setVisible(true);
               this.clnFechaBaja.setVisible(true);
               this.lblFuncionalidadEliminada.setVisible(false);
               this.txtIdTipoPermiso.setEnabled(true);
               this.btnBuscar.setEnabled(true);
               this.txtTitulo.setEnabled(false);
               this.txtDescripcion.setEnabled(false);
               this.txtDescAbreviada.setEnabled(false);
               this.clnFechaAlta.setEnabled(false);
               this.clnFechaBaja.setEnabled(false);
               this.btnAceptar.setEnabled(false);
               this.clnFechaBaja.setForeground(Color.RED);
               this.lblFuncionalidadEliminada.setText("");
               lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reingreso de Tipo de Permiso.png")));
               
            }
    }
     
      private void BuscarFuncionalidad()
    {
          TipoPermiso t = new TipoPermiso();
        
            if(this.txtIdTipoPermiso.getText().equals("") == false)
            {
                  this.id_tipo_permiso = Integer.parseInt(this.txtIdTipoPermiso.getText());
                  if(this.cmbAccion.getSelectedIndex() == 1 || this.cmbAccion.getSelectedIndex() == 2)
                  {
                     t = FabricaLogica.getControladorTipoPermiso().BuscarTipoPermisoPorId(id_tipo_permiso);
                  }
                  else
                  {
                      t = FabricaLogica.getControladorTipoPermiso().BuscarTipoPermisoEliminadosPorId(id_tipo_permiso);
                  }
                  if(t!=null)
                  {
                  
                      this.txtTitulo.setText(t.getNombre());
                      this.txtDescripcion.setText(t.getDescripcion());
                      this.txtDescAbreviada.setText(t.getDesc_abreviada());
                      this.clnFechaAlta.setDate(t.getFecha_hecho());
                      
                      if(this.cmbAccion.getSelectedIndex() == 1 || this.cmbAccion.getSelectedIndex() == 2)
                      {
                         this.lblFuncionalidadEliminada.setVisible(false);
                         this.lblFuncionalidadEliminada.setText("");
                         this.txtTitulo.setForeground(Color.BLACK);
                         this.txtDescripcion.setForeground(Color.BLACK);
                         this.txtDescAbreviada.setForeground(Color.BLACK);
                         this.clnFechaAlta.setForeground(Color.BLACK);
                      
                          if(this.cmbAccion.getSelectedIndex() == 1)
                          {
                               this.txtTitulo.setEnabled(true);
                               this.txtDescripcion.setEnabled(true);
                               this.txtDescAbreviada.setEnabled(true);
                               this.clnFechaAlta.setEnabled(true);
                          }
                          else
                          { 
                               this.clnFechaBaja.setEnabled(true);
                          }
                      
                      }
                      else
                      {  
                         if(this.cmbAccion.getSelectedIndex() == 3)
                         {
                           this.lblFuncionalidadEliminada.setVisible(true);
                           this.lblFuncionalidadEliminada.setText("ELIMINAD0");
                           this.txtTitulo.setForeground(Color.RED);
                           this.txtDescripcion.setForeground(Color.RED);
                           this.txtDescAbreviada.setForeground(Color.RED);
                           this.clnFechaAlta.setForeground(Color.RED);
                         }
                      }
                        this.btnAceptar.setEnabled(true);
                 }
                 else
                 {
                      this.txtTitulo.setText("");
                      this.txtDescripcion.setText("");
                      this.clnFechaAlta.setDate(new Date());
                             
                          this.txtTitulo.setEnabled(false);
                          this.txtDescripcion.setEnabled(false);
                          this.txtDescAbreviada.setEnabled(false);
                          this.clnFechaAlta.setEnabled(false);
                          this.clnFechaBaja.setEnabled(false);
                          this.btnAceptar.setEnabled(false);
                      
                      this.lblMensaje.setText("No existe una tipo de permiso para el Id ingresado. Prueba con otro Id.");
                 }
           }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMTipoPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMTipoPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMTipoPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMTipoPermiso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMTipoPermiso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private org.freixas.jcalendar.JCalendarCombo clnFechaAlta;
    private org.freixas.jcalendar.JCalendarCombo clnFechaBaja;
    private javax.swing.JComboBox<String> cmbAccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAsteriscoFechaBaja;
    private javax.swing.JLabel lblFechaBaja;
    private javax.swing.JLabel lblFuncionalidadEliminada;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlPanelSecundario;
    private javax.swing.JTextField txtDescAbreviada;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtIdTipoPermiso;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
