/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion_computadora.ventanas_auxiliares;

import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import javax.swing.DefaultListModel;
import presentacion_computadora.EstiloFuncionalidad;

/**
 *
 * @author Lourdes Couto
 */
public class CuadroTipoTexto extends javax.swing.JFrame {

    private ActionEvent evento;
    private EstiloFuncionalidad estilo_funcionalidad;
    private DefaultListModel modelo  = new DefaultListModel();
    private String[] lista_fuentes; 
    private Font fuente;
    /**
     * Creates new form CuadroTipoTexto
     */
    public CuadroTipoTexto() {
        try
        {
            initComponents();
            this.CargarDatos();
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
    }

    public CuadroTipoTexto(EstiloFuncionalidad pEstiloFunc, ActionEvent pEvento)
    {
        try
        {
            initComponents();
            this.CargarDatos();
            estilo_funcionalidad = pEstiloFunc;
            evento = pEvento;
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuentes = new javax.swing.JList<>();
        txtFuente = new javax.swing.JTextField();
        txtEstilo = new javax.swing.JTextField();
        txtTamanio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstTamanios = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstEstilos = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtVistaPrevia = new javax.swing.JTextArea();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel1.setText("Selección de Fuentes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Fuente");

        jLabel3.setText("Estilo de Fuente");

        jLabel4.setText("Tamaño");

        lstFuentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFuentesMouseClicked(evt);
            }
        });
        lstFuentes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstFuentesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lstFuentes);

        txtFuente.setEditable(false);

        txtEstilo.setEditable(false);

        txtTamanio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTamanioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamanioKeyTyped(evt);
            }
        });

        lstTamanios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "3", "5", "8", "10", "12", "14", "18", "24", "36", "48", "56", "72" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstTamanios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstTamaniosMousePressed(evt);
            }
        });
        lstTamanios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstTamaniosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(lstTamanios);

        lstEstilos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Común", "Negrita", "Común/Italic", "Negrita/Italic", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEstilos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstEstilosMousePressed(evt);
            }
        });
        lstEstilos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lstEstilosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(lstEstilos);

        jLabel5.setText("Vista Previa");

        txtVistaPrevia.setEditable(false);
        txtVistaPrevia.setColumns(20);
        txtVistaPrevia.setRows(5);
        txtVistaPrevia.setText("The quick brown fox jumps over the lazy dog");
        jScrollPane4.setViewportView(txtVistaPrevia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEstilo)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblError)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarDatos()
    {
         lista_fuentes = GraphicsEnvironment.getLocalGraphicsEnvironment().getAvailableFontFamilyNames();
            
           for(String s: lista_fuentes)
           {
               modelo.addElement(s);
           }
           
           this.lstFuentes.setModel(modelo);
           this.lstFuentes.setSelectedValue("Ubuntu Light", true);
           this.lstEstilos.setSelectedIndex(1);
           this.lstTamanios.setSelectedValue("16", true);
         
           this.txtFuente.setText("Ubuntu Light");
           this.txtTamanio.setText("16");
           this.txtEstilo.setText("Bold");
           
           fuente = new Font("Ubuntu Light", 1, 16);
           this.txtVistaPrevia.setFont(fuente);
    }
    
    private void EstablecerVistaPrevia()
    {       
                fuente = new Font(this.txtFuente.getText(), this.lstEstilos.getSelectedIndex(), Integer.parseInt(this.txtTamanio.getText()));
                this.txtVistaPrevia.setFont(fuente);          
    }
    
    private void lstFuentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFuentesMouseClicked
        // TODO add your handling code here:
        try
        {
            this.txtFuente.setText(this.lstFuentes.getSelectedValue());
            this.EstablecerVistaPrevia();
        }
        catch(Exception ex)
        {
           this.lblError.setText(ex.toString());
        }
        
    }//GEN-LAST:event_lstFuentesMouseClicked

    private void lstEstilosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEstilosMousePressed
        // TODO add your handling code here:
        
        try
        {
            this.txtEstilo.setText(this.lstEstilos.getSelectedValue());
            this.EstablecerVistaPrevia();
        }
        catch(Exception ex)
        {
            this.lblError.setText(ex.toString());
        }
        
    }//GEN-LAST:event_lstEstilosMousePressed

    private void lstTamaniosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTamaniosMousePressed
        // TODO add your handling code here:
        
        try
        {
            this.txtTamanio.setText(this.lstTamanios.getSelectedValue());
            this.EstablecerVistaPrevia();
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
    }//GEN-LAST:event_lstTamaniosMousePressed

    private void lstFuentesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstFuentesKeyReleased
        // TODO add your handling code here:
        
        try
        {
            if((evt.getKeyCode() == 38) || (evt.getKeyCode() == 40))
            {
                this.txtFuente.setText(this.lstFuentes.getSelectedValue());
                this.EstablecerVistaPrevia();
            }
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
        
    }//GEN-LAST:event_lstFuentesKeyReleased

    private void lstEstilosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstEstilosKeyReleased
        // TODO add your handling code here:
        try
        {
            if((evt.getKeyCode() == 38) || (evt.getKeyCode() == 40))
            {
                this.txtEstilo.setText(this.lstEstilos.getSelectedValue());
                this.EstablecerVistaPrevia();
            }
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
        
    }//GEN-LAST:event_lstEstilosKeyReleased

    private void lstTamaniosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstTamaniosKeyReleased
        // TODO add your handling code here:
        try
        {
            if((evt.getKeyCode() == 38) || (evt.getKeyCode() == 40))
            {
                this.txtTamanio.setText(this.lstTamanios.getSelectedValue());
                this.EstablecerVistaPrevia();
            }
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
        
    }//GEN-LAST:event_lstTamaniosKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        try
        {
             this.dispose();
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        try
        {
            this.estilo_funcionalidad.EstablecerTipoFuente(fuente, evt);
            this.dispose();
        }
        catch(Exception ex)
        {
            this.lblError.setText(ex.toString());
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtTamanioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamanioKeyReleased
        // TODO add your handling code here:
        try
        {
            if((Integer.parseInt(this.txtTamanio.getText())>0) && (this.txtTamanio.getText() != ""))
            {
                this.EstablecerVistaPrevia(); 
            }
          
        }
        catch(Exception ex)
        {
             if((Integer.parseInt(this.txtTamanio.getText())<0) || (this.txtTamanio.getText() == ""))
             {
                 this.lblError.setText("Debe ingresar un valor no nulo");
             }
             else
             {
                this.lblError.setText(ex.toString());
             }
        }
        
        
    }//GEN-LAST:event_txtTamanioKeyReleased

    private void txtTamanioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamanioKeyTyped
        // TODO add your handling code here:
        try
        {
              char caracter = evt.getKeyChar(); 

              if(Character.isLetter(caracter)) 
              { 
                  getToolkit().beep(); 
                  evt.consume(); 
                  this.lblError.setText("Ingrese sólamente números"); 
                  //this.lblError.setText("" + evt.getKeyCode()); 
              }
              else
              {
                  this.lblError.setText(""); 
              }
        }
        catch(Exception ex)
        {
             this.lblError.setText(ex.toString());
        }
    }//GEN-LAST:event_txtTamanioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuadroTipoTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuadroTipoTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuadroTipoTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuadroTipoTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CuadroTipoTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblError;
    private javax.swing.JList<String> lstEstilos;
    private javax.swing.JList<String> lstFuentes;
    private javax.swing.JList<String> lstTamanios;
    private javax.swing.JTextField txtEstilo;
    private javax.swing.JTextField txtFuente;
    private javax.swing.JTextField txtTamanio;
    private javax.swing.JTextArea txtVistaPrevia;
    // End of variables declaration//GEN-END:variables
}
