/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion_computadora.ventanas_auxiliares;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import presentacion_computadora.EstiloFuncionalidad;
/**
 *
 * @author Lourdes Couto
 */
public class PantallaColor extends javax.swing.JFrame {

    /**
     * Creates new form PantallaColor
     */
    
    private Color color_elegido;
    private ActionEvent evento;
    private EstiloFuncionalidad estilo_funcionalidad;
    private Image imagen;
    private String archivo;
    
    public PantallaColor() {
        initComponents();
        rdbColor.setSelected(true);
        rdbImagen.setSelected(false);
        this.pantalla_color.setEnabled(true);
        this.lblImagen.setIcon(null);
        this.lblImagen.setEnabled(false);
        this.txtDirectorio.setText("");
        this.btnSeleccionar.setEnabled(false);
    }
    
    public PantallaColor(EstiloFuncionalidad pEstiloFunc, ActionEvent pEvento)
    {
        initComponents();
        estilo_funcionalidad = pEstiloFunc;
        evento = pEvento;
        rdbColor.setSelected(true);
        rdbImagen.setSelected(false);
        this.pantalla_color.setEnabled(true);
        this.lblImagen.setIcon(null);
        this.lblImagen.setEnabled(false);
        this.txtDirectorio.setText("");
        this.btnSeleccionar.setEnabled(false);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDirectorio = new javax.swing.JTextArea();
        pantalla_color = new javax.swing.JColorChooser();
        jLabel3 = new javax.swing.JLabel();
        rdbColor = new javax.swing.JRadioButton();
        rdbImagen = new javax.swing.JRadioButton();
        btnSeleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel1.setText("Selección de Colores y/o Imagenes");

        txtDirectorio.setColumns(20);
        txtDirectorio.setRows(5);
        txtDirectorio.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtDirectorio.setEnabled(false);
        jScrollPane2.setViewportView(txtDirectorio);

        jLabel3.setText("Vista Previa de la Imagen Seleccionada");

        rdbColor.setSelected(true);
        rdbColor.setText("Seleccionar un Color");
        rdbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbColorActionPerformed(evt);
            }
        });

        rdbImagen.setText("Seleccionar una Imagen");
        rdbImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbImagenActionPerformed(evt);
            }
        });

        btnSeleccionar.setText("...");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lblImagen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(pantalla_color, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(rdbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbColor)
                    .addComponent(rdbImagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantalla_color, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnSeleccionar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        try
        {
            color_elegido = pantalla_color.getColor();
            if(this.rdbColor.isSelected() == true)
            {
                estilo_funcionalidad.EstablecerColorFondo(color_elegido, evento);
            }
            else
            {
                estilo_funcionalidad.EstablecerImagenFondo(imagen, archivo ,evento);
            }
            this.dispose();
        }
        catch(Exception ex)
        {
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
         try
        {
             this.dispose();
        }
        catch(Exception ex)
        {
             this.lblMensaje.setText(ex.toString());
        }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rdbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbColorActionPerformed
        // TODO add your handling code here:
        try
        {
            rdbColor.setSelected(true);
            rdbImagen.setSelected(false);
            this.pantalla_color.setEnabled(true);
            this.lblImagen.setIcon(null);
            this.lblImagen.setEnabled(false);
            this.txtDirectorio.setText("");
            this.btnSeleccionar.setEnabled(false);
        }
        catch(Exception ex)
        {
             this.lblMensaje.setText(ex.toString());
        }     
    }//GEN-LAST:event_rdbColorActionPerformed

    private void rdbImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbImagenActionPerformed
        // TODO add your handling code here:
        try
        {
            rdbColor.setSelected(false);
            rdbImagen.setSelected(true);
            this.pantalla_color.setColor(Color.WHITE);
            this.pantalla_color.setEnabled(false);
            this.lblImagen.setEnabled(true);
            this.btnSeleccionar.setEnabled(true);
            this.txtDirectorio.setText("C:\\Users\\Lourdes\\Pictures\\Aviary Photos\\Aviary Stock Photo 1.png");
            File miimagen = new File("C:\\Users\\Lourdes\\Pictures\\Aviary Photos\\Aviary Stock Photo 1.png");
            imagen = ImageIO.read(miimagen);
            lblImagen.setIcon(new javax.swing.ImageIcon(imagen));
        }
        catch(Exception ex)
        {
             this.lblMensaje.setText(ex.toString());
        }     
    }//GEN-LAST:event_rdbImagenActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
       try
        {
            JFileChooser fc = new JFileChooser();
            fc.setCurrentDirectory(new java.io.File("C:\\Users\\Lourdes"));
            fc.setDialogTitle("Seleccione una ubicacion");
            
            if(fc.showOpenDialog(this.btnSeleccionar) == JFileChooser.APPROVE_OPTION)
            {
               if(fc.getSelectedFile().getAbsolutePath().endsWith(".jpg") || fc.getSelectedFile().getAbsolutePath().endsWith(".png") || fc.getSelectedFile().getAbsolutePath().endsWith(".bmp") || fc.getSelectedFile().getAbsolutePath().endsWith(".gif"))
               {
                   this.txtDirectorio.setText(fc.getSelectedFile().getAbsolutePath());
               
                   File miimagen = new File(fc.getSelectedFile().getAbsolutePath());
                   imagen = ImageIO.read(miimagen);
                   lblImagen.setIcon(new javax.swing.ImageIcon(imagen));
                   archivo = fc.getSelectedFile().getPath();
                   this.lblMensaje.setText("");
               }
               else
               {
                   this.lblMensaje.setForeground(Color.RED);
                   this.lblMensaje.setText("Debe elegir archivos con las siguientes extensiones: jpg, png, bmp o gif");
               }
            }
            else
            {
                 this.lblMensaje.setForeground(Color.BLACK);
                 this.lblMensaje.setText("Operacion Cancelada");
            
            }
        }
        catch(Exception ex)
        {
            this.lblMensaje.setForeground(Color.RED);
            this.lblMensaje.setText(ex.toString());
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JColorChooser pantalla_color;
    private javax.swing.JRadioButton rdbColor;
    private javax.swing.JRadioButton rdbImagen;
    private javax.swing.JTextArea txtDirectorio;
    // End of variables declaration//GEN-END:variables
}
